# -*- coding: utf-8 -*-
"""
/***************************************************************************
 FloodPathFinder
                                 A QGIS plugin
 Este plugin é usado para identificar as infraestruturas viárias em pontos suscetívesa inundação
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-03-11
        copyright            : (C) 2024 by Nogueira
        email                : catce.nogueira@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load FloodPathFinder class from file FloodPathFinder.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .flood_path_finder import FloodPathFinder
    return FloodPathFinder(iface)
